version: "3.8"

services:
  notifier:
    container_name: notifier
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true
    driver: bridge